# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 首页
    url: index.html
    weight: 10
  - name: 新闻
    url: news.html
    weight: 20
  - name: 团队
    url: people.html
    weight: 30
  - name: 项目
    url: projects.html
    weight: 40

  - name: 成果
    url: publication.html
    weight: 50

  - name: 联系我们
    url: contact.html
    weight: 60
